version: "3.8"
services:
  postgres:
    image: postgres:16
    env_file:
      - env/postgres.env
    restart: always
    ports:
      - "127.0.0.1:15432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 3s
      retries: 5

volumes:
  pg_data:
